repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-yaml
        args: [--unsafe]
      - id: check-json

  - repo: https://github.com/crate-ci/typos
    rev: v1.35.6
    hooks:
      - id: typos
        args: []

  - repo: local
    hooks:
      - id: nextjs-lint
        name: Next.js Lint
        entry: bash -c 'cd ui && npm run lint'
        language: system
        files: '^ui/.*\.(js|jsx|ts|tsx)$'
        pass_filenames: false

  - repo: local
    hooks:
      - id: nextjs-type-check
        name: Next.js Type Check
        entry: bash -c 'cd ui && npm run build'
        language: system
        files: '^ui/.*\.(js|jsx|ts|tsx)$'
        pass_filenames: false

ci:
  autofix_commit_msg: |
    [pre-commit.ci] Add auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [nextjs-lint, nextjs-type-check]
  submodules: false
