services:
  frontend:
    profiles: ["frontend"]
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_HOST=${BACKEND_HOST}
    image: tender-tales/platform:frontend-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=${BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./tender_tales
      dockerfile: Dockerfile.api
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - FRONTEND_PORT=${FRONTEND_PORT}
    image: tender-tales/platform:backend-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - EARTH_ENGINE_PROJECT_ID=${EARTH_ENGINE_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/earthengine-credentials
      - DEBUG=${DEBUG}
      - RELOAD=${RELOAD:-false}
    secrets:
      - earthengine-credentials
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mcp-server:
    build:
      context: ./tender_tales
      dockerfile: Dockerfile.mcp
      args:
        - MCP_PORT=${MCP_PORT}
    image: tender-tales/platform:mcp-server-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${MCP_PORT}:${MCP_PORT}"
    environment:
      - MCP_PORT=${MCP_PORT}
      - EARTH_ENGINE_PROJECT_ID=${EARTH_ENGINE_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/earthengine-credentials
      - DEBUG=${DEBUG}
    secrets:
      - earthengine-credentials
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MCP_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge

secrets:
  earthengine-credentials:
    file: ./tender_tales/credentials.json
