services:
  frontend:
    profiles: ["frontend"]
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}
        - BACKEND_HOST=${BACKEND_HOST}
    image: tender-tales/platform:frontend-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=${BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
      - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./tender_tales
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - FRONTEND_PORT=${FRONTEND_PORT}
    image: tender-tales/platform:backend-${BUILD_ID}
    env_file: .env.production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - EARTH_ENGINE_PROJECT_ID=${EARTH_ENGINE_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - DEBUG=${DEBUG}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
