#!/bin/bash

echo "Setting up Google OAuth credentials..."
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://console.cloud.google.com/apis/credentials?project=ocean-health-468302"
echo "2. Click 'CREATE CREDENTIALS' > 'OAuth 2.0 Client ID'"
echo "3. If prompted to configure OAuth consent screen:"
echo "   - Choose 'External' user type"
echo "   - App name: 'Tender Tales Platform'"
echo "   - User support email: amrit110@gmail.com"
echo "   - Developer contact: amrit110@gmail.com"
echo "   - Save and continue through the steps"
echo "4. For OAuth client:"
echo "   - Application type: Web application"
echo "   - Name: Tender Tales OAuth Client"
echo "   - Authorized JavaScript origins: http://localhost:3000"
echo "   - Authorized redirect URIs: http://localhost:3000/api/auth/callback/google"
echo "5. Copy the Client ID and Client Secret"
echo "6. Update .env.development with the real credentials"
echo ""
