name: build and deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  REPOSITORY: tender-tales
  SERVICE_BACKEND: tender-tales-backend
  SERVICE_FRONTEND: tender-tales-frontend
  SERVICE_MCP: tender-tales-mcp
  REGION: us-central1
  BUILD_ID: ${{ github.sha }}
  # Common environment variables for builds
  BACKEND_PORT: 8000
  FRONTEND_PORT: 3000
  MCP_PORT: 8001
  BACKEND_HOST: localhost
  DEBUG: false

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create Earth Engine Credentials (for build)
        run: echo '${{ secrets.EARTH_ENGINE_CREDENTIALS }}' > tender_tales/credentials.json

      - name: Set up environment variables
        run: |
          cat > .env.production << EOF
          BACKEND_PORT=${{ env.BACKEND_PORT }}
          FRONTEND_PORT=${{ env.FRONTEND_PORT }}
          BACKEND_HOST=${{ env.BACKEND_HOST }}
          EARTH_ENGINE_PROJECT_ID=test-project
          DEBUG=${{ env.DEBUG }}
          EOF

      - name: Build backend image
        run: |
          export COMPOSE_PROJECT_NAME=tender-tales-ci
          export BACKEND_PORT=${{ env.BACKEND_PORT }}
          export FRONTEND_PORT=${{ env.FRONTEND_PORT }}
          export BACKEND_HOST=${{ env.BACKEND_HOST }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          export DEBUG=${{ env.DEBUG }}
          export BUILD_ID=${{ env.BUILD_ID }}
          docker compose build backend

      - name: Build MCP server image
        run: |
          export COMPOSE_PROJECT_NAME=tender-tales-ci
          export MCP_PORT=${{ env.MCP_PORT }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          export DEBUG=${{ env.DEBUG }}
          export BUILD_ID=${{ env.BUILD_ID }}
          docker build -t tender-tales/platform:mcp-server-${{ env.BUILD_ID }} ./tender_tales/mcp_server

      - name: Test MCP server functionality
        if: github.actor != 'dependabot[bot]'
        run: |
          export MCP_PORT=${{ env.MCP_PORT }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          export DEBUG=${{ env.DEBUG }}
          export BUILD_ID=${{ env.BUILD_ID }}

          # Run the MCP server container in detached mode
          docker run -d \
            --name mcp-server-test-${{ env.BUILD_ID }} \
            -p ${{ env.MCP_PORT }}:${{ env.MCP_PORT }} \
            -e EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }} \
            -e MCP_PORT=${{ env.MCP_PORT }} \
            -e DEBUG=${{ env.DEBUG }} \
            tender-tales/platform:mcp-server-${{ env.BUILD_ID }}

          # Wait for server to start
          sleep 30

          # Check if container is running
          docker ps | grep mcp-server-test-${{ env.BUILD_ID }}

          # Check container logs for startup issues
          echo "=== MCP Server Logs ==="
          docker logs mcp-server-test-${{ env.BUILD_ID }}

          # Run the test client inside the container to test MCP functionality
          echo "=== Running MCP Client Tests ==="
          docker exec mcp-server-test-${{ env.BUILD_ID }} uv run python test_mcp_client.py

          # Check server health by testing HTTP endpoint if available
          echo "=== Testing Server Health ==="
          docker exec mcp-server-test-${{ env.BUILD_ID }} curl -f http://localhost:${{ env.MCP_PORT }}/health || echo "Health endpoint not available (expected for MCP-only server)"

          # Clean up
          docker stop mcp-server-test-${{ env.BUILD_ID }}
          docker rm mcp-server-test-${{ env.BUILD_ID }}

      - name: Google Auth for Testing
        if: github.actor != 'dependabot[bot]'
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: 'earth-engine-service@ocean-health-468302.iam.gserviceaccount.com'

      - name: Test backend functionality
        if: github.actor != 'dependabot[bot]'
        run: |
          export COMPOSE_PROJECT_NAME=tender-tales-ci
          export BACKEND_PORT=${{ env.BACKEND_PORT }}
          export FRONTEND_PORT=${{ env.FRONTEND_PORT }}
          export BACKEND_HOST=${{ env.BACKEND_HOST }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          export DEBUG=${{ env.DEBUG }}
          export BUILD_ID=${{ env.BUILD_ID }}
          docker compose up -d backend
          sleep 30
          docker compose ps
          docker compose logs backend
          docker compose down

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-backend
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Google Auth
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: 'earth-engine-service@ocean-health-468302.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Create Earth Engine Credentials
        run: echo '${{ secrets.EARTH_ENGINE_CREDENTIALS }}' > tender_tales/credentials.json

      - name: Set up environment variables
        run: |
          cat > .env.production << EOF
          BACKEND_PORT=${{ env.BACKEND_PORT }}
          FRONTEND_PORT=${{ env.FRONTEND_PORT }}
          BACKEND_HOST=${{ env.BACKEND_HOST }}
          EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          DEBUG=${{ env.DEBUG }}
          EOF

      - name: Build and push backend image
        run: |
          export COMPOSE_PROJECT_NAME=tender-tales-gcp
          export BACKEND_PORT=${{ env.BACKEND_PORT }}
          export FRONTEND_PORT=${{ env.FRONTEND_PORT }}
          export BACKEND_HOST=${{ env.BACKEND_HOST }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          export DEBUG=${{ env.DEBUG }}
          export BUILD_ID=${{ env.BUILD_ID }}
          docker compose build backend

          # Tag and push backend
          docker tag tender-tales/platform:backend-${{ env.BUILD_ID }} \
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_BACKEND }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_BACKEND }}:${{ github.sha }}

      - name: Build and push MCP server image
        run: |
          export BUILD_ID=${{ env.BUILD_ID }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          docker build -t tender-tales/platform:mcp-server-${{ env.BUILD_ID }} ./tender_tales/mcp_server

          # Tag and push MCP server
          docker tag tender-tales/platform:mcp-server-${{ env.BUILD_ID }} \
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_MCP }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_MCP }}:${{ github.sha }}

      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_BACKEND }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_BACKEND }}:${{ github.sha }}
          flags: '--allow-unauthenticated --memory=1Gi --cpu=1 --timeout=300 --max-instances=10 --cpu-boost'
          env_vars: |
            EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
            GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

      - name: Deploy MCP Server to Cloud Run
        id: deploy-mcp
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_MCP }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_MCP }}:${{ github.sha }}
          flags: '--allow-unauthenticated --memory=1Gi --cpu=1 --timeout=300 --max-instances=10 --cpu-boost'
          env_vars: |
            EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
            GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

      - name: Build and push frontend image with backend URL
        run: |
          export COMPOSE_PROJECT_NAME=tender-tales-gcp
          export BACKEND_PORT=${{ env.BACKEND_PORT }}
          export FRONTEND_PORT=${{ env.FRONTEND_PORT }}
          export BACKEND_HOST=${{ env.BACKEND_HOST }}
          export EARTH_ENGINE_PROJECT_ID=${{ secrets.EARTH_ENGINE_PROJECT_ID }}
          export DEBUG=${{ env.DEBUG }}
          export BUILD_ID=${{ env.BUILD_ID }}

          # Build frontend with the deployed backend URL
          docker compose build frontend \
            --build-arg NEXT_PUBLIC_MAPBOX_API_KEY=${{ secrets.MAPBOX_API_KEY }} \
            --build-arg NEXT_PUBLIC_BACKEND_URL=${{ steps.deploy-backend.outputs.url }}

          # Tag and push frontend
          docker tag tender-tales/platform:frontend-${{ env.BUILD_ID }} \
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_FRONTEND }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_FRONTEND }}:${{ github.sha }}

      - name: Deploy Frontend to Cloud Run
        id: deploy-frontend
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_FRONTEND }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_FRONTEND }}:${{ github.sha }}
          flags: '--allow-unauthenticated --memory=512Mi --cpu=1 --timeout=300 --max-instances=10'

      - name: Show deployment URLs
        run: |
          echo "Backend URL: ${{ steps.deploy-backend.outputs.url }}"
          echo "MCP Server URL: ${{ steps.deploy-mcp.outputs.url }}"
          echo "Frontend URL: ${{ steps.deploy-frontend.outputs.url }}"
